### ISSUE TITLE
Support other TODO notations

### ISSUE THREAD

**Issue by chrisparnin** [chrisparnin/attachables#1]
FIXME, todo, XXX, etc are not triggered.

**Comment by AMDG2** [comment]
It would be great if you can also support doxygen notation, examples:
```C#
// @TODO Support with @ before todo

//! @TODO Support for //! opening inline comment

/**
 * @TODO support inside multiline comment
 */
```

Thanks for the great extension !

**Comment by chrisparnin** [comment]
All these except multiline comments supported in 1.5.7 in gallery.

Will have to address multiline in future issue.
